apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-deploy
  labels:
    app: tenants
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tenants
  template:
    metadata:
      labels:
        app: tenants
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "meridian-tenants"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: tenants
        image: "gbl-devlnx2.meridianksi.net:32443/meridian.tenants.web.api:1.1.0-dev.18357_22074.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: CONNECTION_STRING
          value: "User ID = postgres; Password = password; Host = postgres-service; Port = 5432; Database = Tenants; Pooling = true;"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
