apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: tenant-service # this is name of the service
      port:
        number: 8083 # this is the service's cluster port exposed to be talked to a lot
  rules:
  - host: app.tenants.com # add this entry to your host file - 127.0.0.1 www.tenants.com
    http:
      paths:
        - path: "/tenants"
          pathType: Prefix
          backend:
            service:
             name: tenant-service # this is name of the service
             port:
                number: 8083 # this is the service's cluster port exposed to be talked to a lot