apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: nginx-service
      port:
        number: 8086
  rules:
  - host: foo.bar.com # add this entry to your host file - 127.0.0.1 foo.bar.com
    http:
      paths:
        - path: "/bar"
          pathType: Prefix
          backend:
            service:
             name: tenant-service # this is name of the service
             port:
                number: 8083 # this is the service's cluster port exposed to be talked to a lot
        - path: "/foo"
          pathType: Prefix
          backend:
            service:
             name: tenant-service-clusterip # this is name of the service
             port:
                number: 8084 # this is the service's cluster port exposed to be talked to a lot