apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  labels:
    app: tenants  
spec:
  type: NodePort
  selector:
    app: tenants
  ports:
    - protocol: TCP
      port: 8083 #Cluster IP Level
      targetPort: 80
      nodePort: 31000  #External Port
  