apiVersion: v2 #Helm API Version
name: postgres-chart
description: A helm chart for Kubernetes - Postgres
keywords:
  - "postgres"
type: application
appVersion: 1.0.0 # Version of the Application
version: 1.0.0 # Version of the chart
